### ISSUE TITLE
Tutorials docker-compose failed

### ISSUE THREAD

**Issue by Srceh** [IRC-SPHERE/Hyperstream-Dockerfiles#9]
I think it's simply because hyperstream_config.json is no longer in examples but in the root folder...

Step 8/10 : RUN sed -i -e 's/localhost/hyperstream-mongo/g' examples/hyperstream_config.json
 ---> Running in 745d6c769398
sed: can't read examples/hyperstream_config.json: No such file or directory

**Comment by So-Cool** [comment]
That's right. Instead of using the latest commit of hyperstream we should pull specific tag in the docker build, I guess.

**Comment by So-Cool** [comment]
@perellonieto have you merged the tutorials into the master branch? This seems to be broken because of your changes.

**Comment by perellonieto** [comment]
Yes, we decided to merge the tutorial branch into the master. It is possible that when merging one of the files was lost. I will take a look at the location of the examples/hyperstream_config.json.
I also changed the docker-files for the tutorial trying to use the master branch instead of the tutorials branch. I hope I didn't break anything.
The strange thing is that on my laptop following the steps to run the docker-tutorials worked perfectly, and it did not complain about the examples/hyperstream_config.json file.

**Comment by tdiethe** [comment]
You can point hyperstream to a config file in another location if that's simpler, rather than having two? Or another option would be to add a `ln -s` statement into the docker file?

**Comment by perellonieto** [comment]
I will create the corresponding hyperstream_config.json in each folder. The purpose of each configuration file is different and shouldn't be the same.

In the case of the tutorial, the plugins that are being used are simple examples that can be modified to understand how to create tools. These could be broken and should not affect the configuration on the root folder.

The configuration file in the root folder should be a basic configuration that can be used as a template. In principle, this one should not contain the plugins for the tutorial, as these are really basic and not useful in the general case.

**Comment by perellonieto** [comment]
I tried the tutorial now and it is working perfectly.
@Srceh can you cofirm that the error that you mentioned doesn't happen anymore?
You may need to clean the images in your docker in order to be sure that you run the latest version. Just be sure that the following command does not show images like in my case
```bash
$ docker images
REPOSITORY                                TAG                 IMAGE ID            CREATED             SIZE
hyperstreamtutorials_hyperstream-viewer   latest              b5074c2ec695        8 minutes ago       680MB
hyperstreamtutorials_hyperstream          latest              62a472edc2f0        11 minutes ago      677MB
hyperstreamtutorials_hyperstream-mongo    latest              0e5fce517720        14 minutes ago      384MB
ircsphere/hyperstream                     latest              f40ca239c61c        33 hours ago        520MB
ubuntu                                    16.04               14f60031763d        3 weeks ago         120MB
```
If it shows images, try to clean them following the instructions [here](https://docs.docker.com/engine/reference/commandline/rmi/).

If you can confirm that it works we can close this issue.

**Comment by So-Cool** [comment]
I can see that we have tags in the hyperstream repo. What we should do is follow the same tags with the docker images (hypersteram, viewer and tutorials) i.e. the latest hyperstream docker image should be 0.3.6. This should resolve all of the issues.

The hyperstream-mongo image does not require versioning.

(I'll try to sort it out by the end of today.)

**Comment by Srceh** [comment]
@perellonieto Still the same error, I did remove all the previous images...

Step 8/10 : RUN sed -i -e 's/localhost/hyperstream-mongo/g' examples/hyperstream_config.json
 ---> Running in 89e2ab065445
sed: can't read examples/hyperstream_config.json: No such file or directory
ERROR: Service 'hyperstream' failed to build: The command '/bin/sh -c sed -i -e 's/localhost/hyperstream-mongo/g' examples/hyperstream_config.json' returned a non-zero code: 2

**Comment by Srceh** [comment]
@perellonieto It's working now.

**Comment by perellonieto** [comment]
Great !! Closing :)
